all:
	g++ -Wall -c carta.cpp -o carta.o
	g++ -Wall -c baralho.cpp -o baralho.o
	g++ -Wall -c pilha.cpp -o pilha.o
	g++ -Wall -c main.cpp -o main.o
	g++ -Wall -c monte.cpp -o monte.o
	g++ -Wall -c fundacao.cpp -o fundacao.o
	g++ -Wall -c yukon.cpp -o yukon.o
	g++ -Wall -c yukonCLI.cpp -o yukonCLI.o
	g++ -Wall main.o carta.o baralho.o pilha.o monte.o fundacao.o yukon.o yukonCLI.o -o yukon.exe

